# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Jan 23 00:48:41 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1169, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_sec1 = QtGui.QLabel(self.centralwidget)
        self.label_sec1.setObjectName(_fromUtf8("label_sec1"))
        self.gridLayout.addWidget(self.label_sec1, 0, 0, 1, 1)
        self.doubleSpinBox_sec1_ask = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec1_ask.setReadOnly(True)
        self.doubleSpinBox_sec1_ask.setDecimals(6)
        self.doubleSpinBox_sec1_ask.setMinimum(0.0)
        self.doubleSpinBox_sec1_ask.setMaximum(100000.0)
        self.doubleSpinBox_sec1_ask.setObjectName(_fromUtf8("doubleSpinBox_sec1_ask"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec1_ask, 1, 0, 1, 1)
        self.doubleSpinBox_sec1_bid = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec1_bid.setReadOnly(True)
        self.doubleSpinBox_sec1_bid.setDecimals(6)
        self.doubleSpinBox_sec1_bid.setMaximum(100000.0)
        self.doubleSpinBox_sec1_bid.setObjectName(_fromUtf8("doubleSpinBox_sec1_bid"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec1_bid, 2, 0, 1, 1)
        self.label_sec2 = QtGui.QLabel(self.centralwidget)
        self.label_sec2.setObjectName(_fromUtf8("label_sec2"))
        self.gridLayout.addWidget(self.label_sec2, 0, 2, 1, 1)
        self.doubleSpinBox_sec2_ask = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec2_ask.setReadOnly(True)
        self.doubleSpinBox_sec2_ask.setDecimals(6)
        self.doubleSpinBox_sec2_ask.setMaximum(100000.0)
        self.doubleSpinBox_sec2_ask.setObjectName(_fromUtf8("doubleSpinBox_sec2_ask"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec2_ask, 1, 2, 1, 1)
        self.doubleSpinBox_sec2_bid = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec2_bid.setReadOnly(True)
        self.doubleSpinBox_sec2_bid.setDecimals(6)
        self.doubleSpinBox_sec2_bid.setMaximum(100000.0)
        self.doubleSpinBox_sec2_bid.setObjectName(_fromUtf8("doubleSpinBox_sec2_bid"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec2_bid, 2, 2, 1, 1)
        self.label_sec3 = QtGui.QLabel(self.centralwidget)
        self.label_sec3.setObjectName(_fromUtf8("label_sec3"))
        self.gridLayout.addWidget(self.label_sec3, 0, 4, 1, 1)
        self.doubleSpinBox_sec2_askAmount = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec2_askAmount.setReadOnly(True)
        self.doubleSpinBox_sec2_askAmount.setDecimals(6)
        self.doubleSpinBox_sec2_askAmount.setMaximum(99999.99)
        self.doubleSpinBox_sec2_askAmount.setObjectName(_fromUtf8("doubleSpinBox_sec2_askAmount"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec2_askAmount, 1, 3, 1, 1)
        self.doubleSpinBox_sec3_ask = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec3_ask.setReadOnly(True)
        self.doubleSpinBox_sec3_ask.setDecimals(6)
        self.doubleSpinBox_sec3_ask.setMaximum(100000.0)
        self.doubleSpinBox_sec3_ask.setObjectName(_fromUtf8("doubleSpinBox_sec3_ask"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec3_ask, 1, 4, 1, 1)
        self.doubleSpinBox_sec3_bid = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec3_bid.setReadOnly(True)
        self.doubleSpinBox_sec3_bid.setDecimals(6)
        self.doubleSpinBox_sec3_bid.setMaximum(100000.0)
        self.doubleSpinBox_sec3_bid.setObjectName(_fromUtf8("doubleSpinBox_sec3_bid"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec3_bid, 2, 4, 1, 1)
        self.doubleSpinBox_sec1_askAmount = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec1_askAmount.setReadOnly(True)
        self.doubleSpinBox_sec1_askAmount.setDecimals(6)
        self.doubleSpinBox_sec1_askAmount.setMaximum(99999.99)
        self.doubleSpinBox_sec1_askAmount.setObjectName(_fromUtf8("doubleSpinBox_sec1_askAmount"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec1_askAmount, 1, 1, 1, 1)
        self.doubleSpinBox_sec1_bidAmount = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec1_bidAmount.setReadOnly(True)
        self.doubleSpinBox_sec1_bidAmount.setDecimals(6)
        self.doubleSpinBox_sec1_bidAmount.setMaximum(99999.99)
        self.doubleSpinBox_sec1_bidAmount.setObjectName(_fromUtf8("doubleSpinBox_sec1_bidAmount"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec1_bidAmount, 2, 1, 1, 1)
        self.doubleSpinBox_sec2_bidAmount = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec2_bidAmount.setReadOnly(True)
        self.doubleSpinBox_sec2_bidAmount.setDecimals(6)
        self.doubleSpinBox_sec2_bidAmount.setMaximum(99999.99)
        self.doubleSpinBox_sec2_bidAmount.setObjectName(_fromUtf8("doubleSpinBox_sec2_bidAmount"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec2_bidAmount, 2, 3, 1, 1)
        self.doubleSpinBox_sec3_askAmount = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec3_askAmount.setReadOnly(True)
        self.doubleSpinBox_sec3_askAmount.setDecimals(6)
        self.doubleSpinBox_sec3_askAmount.setMaximum(99999.99)
        self.doubleSpinBox_sec3_askAmount.setObjectName(_fromUtf8("doubleSpinBox_sec3_askAmount"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec3_askAmount, 1, 5, 1, 1)
        self.doubleSpinBox_sec3_bidAmount = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sec3_bidAmount.setReadOnly(True)
        self.doubleSpinBox_sec3_bidAmount.setDecimals(6)
        self.doubleSpinBox_sec3_bidAmount.setMaximum(99999.99)
        self.doubleSpinBox_sec3_bidAmount.setObjectName(_fromUtf8("doubleSpinBox_sec3_bidAmount"))
        self.gridLayout.addWidget(self.doubleSpinBox_sec3_bidAmount, 2, 5, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_result = QtGui.QLabel(self.centralwidget)
        self.label_result.setObjectName(_fromUtf8("label_result"))
        self.horizontalLayout.addWidget(self.label_result)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_lag = QtGui.QLabel(self.centralwidget)
        self.label_lag.setObjectName(_fromUtf8("label_lag"))
        self.horizontalLayout_4.addWidget(self.label_lag)
        self.spinBox_lag = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_lag.setReadOnly(True)
        self.spinBox_lag.setMaximum(100000)
        self.spinBox_lag.setObjectName(_fromUtf8("spinBox_lag"))
        self.horizontalLayout_4.addWidget(self.spinBox_lag)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.tableView_history = QtGui.QTableView(self.centralwidget)
        self.tableView_history.setObjectName(_fromUtf8("tableView_history"))
        self.tableView_history.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tableView_history)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_pause = QtGui.QPushButton(self.centralwidget)
        self.pushButton_pause.setObjectName(_fromUtf8("pushButton_pause"))
        self.horizontalLayout_2.addWidget(self.pushButton_pause)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1169, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyTrader", None))
        self.label_sec1.setText(_translate("MainWindow", "<html><head/><body><p>BTC/USD</p></body></html>", None))
        self.label_sec2.setText(_translate("MainWindow", "LTC/BTC", None))
        self.label_sec3.setText(_translate("MainWindow", "LTC/USD", None))
        self.label_result.setText(_translate("MainWindow", "TextLabel", None))
        self.label_lag.setText(_translate("MainWindow", "API lag", None))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause / resume", None))
        self.pushButton.setText(_translate("MainWindow", "Exit", None))

